services:
  db_postgres:
    image: postgres:17-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Cnic2024#kiki
      POSTGRES_DB: dbTricks
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django_app:
    build: .
    depends_on:
      - db_postgres
    ports:
      - 80:8000
volumes:
  postgres_data: