version: "3"
services:
  db_postgres:
    image: postgres:17-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Cnic2024#kiki
      POSTGRES_DB: dbTricks
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django_app:
    build: .
    volumes:
      - static:/code/static
      - .:/code
    depends_on:
      - db_postgres
  nginx:
    image: nginx:1.27-alpine3.20
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
    depends_on:
      - django_app
volumes:
  .:
  postgres_data:
  static: