# Generated by Django 5.1.2 on 2025-04-04 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
