# Generated by Django 5.1.2 on 2025-04-04 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_remove_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
