# Generated by Django 5.1.2 on 2024-11-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorito', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products_Tendencias',
        ),
    ]
