# Generated by Django 5.1.2 on 2024-11-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorito', '0002_rename_product_products_tendencias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products_Tendencias',
        ),
    ]
