# Generated by Django 5.1.2 on 2024-11-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrarse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=30)),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
    ]
