# Generated by Django 5.1.2 on 2024-11-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrarse',
            name='contrasenia',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
