# Generated by Django 5.1.2 on 2024-11-11 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_registrarse_contrasenia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registrarse',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='contrasenia',
            new_name='contraseña',
        ),
    ]
