# Generated by Django 5.1.2 on 2024-11-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_rename_registrarse_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
